# Site settings
title: Blog site by Harsh Narang
description: "Blog site for publishing blogs related to Homebrew"
url: "http://harshnarang8.github.io"
author:
  name: "Blogs by Harsh"
  email: "harshnarang8@gmail.com"
  url: "https://home.iitk.ac.in/harshn"

# Build settings
baseurl: / # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
gems:
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
version: "1.0.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false
